---
apiVersion: v1
kind: Pod
metadata:
  name: cm-pod
  labels:
    name: sample-po
spec:
  containers:
    - name: my-pod
      image: nginx
      envFrom:
      - configMapRef:
          name: sample-cm


